2025-06-22 11:30:12,189 INFO: Feelog startup [in D:\Feelog\app\__init__.py:75]
2025-06-22 12:51:49,451 INFO: Feelog startup [in D:\Feelog\app\__init__.py:75]
2025-06-22 12:52:02,837 ERROR: Exception on /auth/reset_password_request [POST] [in D:\Feelog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Feelog\app\auth\routes.py", line 69, in reset_password_request
    send_password_reset_email(user)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\Feelog\app\auth\email.py", line 8, in send_password_reset_email
    send_email(_('[Feelog] Reset Your Password'),
               ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Feelog\venv\Lib\site-packages\flask_babel\__init__.py", line 756, in gettext
    return get_domain().gettext(*args, **kwargs)
           ~~~~~~~~~~^^
  File "D:\Feelog\venv\Lib\site-packages\flask_babel\__init__.py", line 750, in get_domain
    ctx.babel_domain = get_babel().instance.domain_instance
                       ~~~~~~~~~^^
  File "D:\Feelog\venv\Lib\site-packages\flask_babel\__init__.py", line 46, in get_babel
    return app.extensions['babel']
           ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'babel'
2025-06-22 12:53:23,827 INFO: Feelog startup [in D:\Feelog\app\__init__.py:75]
2025-06-22 12:53:31,743 ERROR: Exception on /auth/reset_password_request [POST] [in D:\Feelog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Feelog\app\auth\routes.py", line 69, in reset_password_request
    send_password_reset_email(user)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\Feelog\app\auth\email.py", line 11, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              user=user, token=token),
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Feelog\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\Feelog\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\Feelog\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Feelog\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Feelog\app\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "D:\Feelog\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2025-06-22 13:01:46,110 INFO: Feelog startup [in D:\Feelog\app\__init__.py:75]
2025-06-22 13:01:53,394 ERROR: Exception on /auth/reset_password_request [POST] [in D:\Feelog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Feelog\app\auth\routes.py", line 69, in reset_password_request
    send_password_reset_email(user)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\Feelog\app\auth\email.py", line 11, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              user=user, token=token),
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Feelog\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\Feelog\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\Feelog\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Feelog\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Feelog\app\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Feelog\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "D:\Feelog\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2025-06-22 13:02:50,987 INFO: Feelog startup [in D:\Feelog\app\__init__.py:75]
